spark.hadoop.fs.s3a.endpoint                http://minio:9000
spark.hadoop.fs.s3a.path.style.access       true
spark.hadoop.fs.s3a.access.key              minio123
spark.hadoop.fs.s3a.secret.key              minio123
spark.hadoop.fs.s3a.impl                    org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled  false
spark.sql.catalogImplementation             hive
spark.hadoop.hive.metastore.uris            thrift://hive-metastore:9083
spark.sql.warehouse.dir                     s3a://lakehouse/
spark.pyspark.python                        /opt/conda/bin/python
spark.pyspark.driver.python                 /opt/conda/bin/python
spark.executorEnv.PYSPARK_PYTHON            /opt/conda/bin/python
spark.executorEnv.PYSPARK_DRIVER_PYTHON     /opt/conda/bin/python
